#############################################################################
# Makefile for building: car.app/Contents/MacOS/car
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  car.pro
# Template: app
# Command: /Users/Jc_tecklenburg/Qt/5.3/clang_64/bin/qmake -o Makefile car.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt/5.3/clang_64/mkspecs/macx-clang -I. -I../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -F/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.6
LIBS          = $(SUBLIBS) -F/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/Jc_tecklenburg/Qt/5.3/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		physicsengine.cpp \
		ball.cpp \
		vector.cpp \
		car.cpp moc_main.cpp
OBJECTS       = main.o \
		physicsengine.o \
		ball.o \
		vector.o \
		car.o \
		moc_main.o
DIST          = ../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		car.pro main.cpp \
		physicsengine.cpp \
		ball.cpp \
		vector.cpp \
		car.cpp
QMAKE_TARGET  = car
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = car.app/Contents/MacOS/car

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.6 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile car.app/Contents/PkgInfo car.app/Contents/Resources/empty.lproj car.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d car.app/Contents/MacOS/ || mkdir -p car.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: car.pro ../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.3/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.3/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.3/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.3/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.3/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.3/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.3/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.3/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.3/clang_64/mkspecs/features/lex.prf \
		car.pro \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile car.pro
../../Qt/5.3/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.3/clang_64/mkspecs/qdevice.pri:
../../Qt/5.3/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.3/clang_64/mkspecs/common/shell-unix.conf:
../../Qt/5.3/clang_64/mkspecs/common/unix.conf:
../../Qt/5.3/clang_64/mkspecs/common/mac.conf:
../../Qt/5.3/clang_64/mkspecs/common/macx.conf:
../../Qt/5.3/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.3/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.3/clang_64/mkspecs/common/clang.conf:
../../Qt/5.3/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.3/clang_64/mkspecs/qconfig.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.3/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.3/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.3/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.3/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.3/clang_64/mkspecs/features/spec_post.prf:
../../Qt/5.3/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.3/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.3/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.3/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.3/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.3/clang_64/mkspecs/features/qt.prf:
../../Qt/5.3/clang_64/mkspecs/features/resources.prf:
../../Qt/5.3/clang_64/mkspecs/features/moc.prf:
../../Qt/5.3/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.3/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.3/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.3/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.3/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.3/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.3/clang_64/mkspecs/features/lex.prf:
car.pro:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile car.pro

qmake_all: FORCE

car.app/Contents/PkgInfo: 
	@test -d car.app/Contents || mkdir -p car.app/Contents
	@$(DEL_FILE) car.app/Contents/PkgInfo
	@echo "APPL????" >car.app/Contents/PkgInfo
car.app/Contents/Resources/empty.lproj: 
	@test -d car.app/Contents/Resources || mkdir -p car.app/Contents/Resources
	@touch car.app/Contents/Resources/empty.lproj
	
car.app/Contents/Info.plist: 
	@test -d car.app/Contents || mkdir -p car.app/Contents
	@$(DEL_FILE) car.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,JCT.car,g" -e "s,@EXECUTABLE@,car,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.3/clang_64/mkspecs/macx-clang/Info.plist.app >car.app/Contents/Info.plist
dist: 
	@test -d .tmp/car1.0.0 || mkdir -p .tmp/car1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/car1.0.0/ && $(COPY_FILE) --parents main.h ball.h car.h vector.h physicsengine.h .tmp/car1.0.0/ && $(COPY_FILE) --parents main.cpp physicsengine.cpp ball.cpp vector.cpp car.cpp .tmp/car1.0.0/ && (cd `dirname .tmp/car1.0.0` && $(TAR) car1.0.0.tar car1.0.0 && $(COMPRESS) car1.0.0.tar) && $(MOVE) `dirname .tmp/car1.0.0`/car1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/car1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r car.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_main.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main.cpp
moc_main.cpp: ../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		main.h
	/Users/Jc_tecklenburg/Qt/5.3/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/mkspecs/macx-clang -I/Users/Jc_tecklenburg/Git/genetic_cars -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtGui.framework/Headers -I/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib/QtCore.framework/Headers -F/Users/Jc_tecklenburg/Qt/5.3/clang_64/lib main.h -o moc_main.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QtGui \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessible.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessiblebridge.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbitmap.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qicon.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengine.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengineplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimageiohandler.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagewriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpicture.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpictureformatplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmapcache.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcursor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdrag.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericpluginfactory.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qinputmethod.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qkeysequence.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qoffscreensurface.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglcontext.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpalette.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qscreen.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsessionmanager.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstylehints.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurface.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurfaceformat.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtouchdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindow.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindowdefs.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericmatrix.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qquaternion.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengl.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglbuffer.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglframebufferobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglfunctions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpixeltransferoptions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglshaderprogram.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltexture.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltimerquery.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglversionfunctions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbackingstore.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbrush.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagedpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagelayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagesize.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintengine.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainterpath.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpdfwriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpen.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpolygon.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qregion.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrgb.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtransform.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qabstracttextdocumentlayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontdatabase.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontinfo.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qglyphrun.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrawfont.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstatictext.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextcursor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocument.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentfragment.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentwriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextformat.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlist.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextoption.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtexttable.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdesktopservices.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvalidator.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtguiversion.h \
		main.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		physicsengine.h \
		ball.h \
		vector.h \
		car.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

physicsengine.o: physicsengine.cpp ../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QtGui \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessible.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessiblebridge.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbitmap.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qicon.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengine.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengineplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimageiohandler.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagewriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpicture.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpictureformatplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmapcache.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcursor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdrag.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericpluginfactory.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qinputmethod.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qkeysequence.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qoffscreensurface.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglcontext.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpalette.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qscreen.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsessionmanager.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstylehints.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurface.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurfaceformat.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtouchdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindow.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindowdefs.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericmatrix.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qquaternion.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengl.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglbuffer.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglframebufferobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglfunctions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpixeltransferoptions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglshaderprogram.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltexture.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltimerquery.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglversionfunctions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbackingstore.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbrush.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagedpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagelayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagesize.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintengine.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainterpath.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpdfwriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpen.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpolygon.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qregion.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrgb.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtransform.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qabstracttextdocumentlayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontdatabase.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontinfo.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qglyphrun.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrawfont.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstatictext.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextcursor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocument.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentfragment.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentwriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextformat.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlist.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextoption.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtexttable.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdesktopservices.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvalidator.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtguiversion.h \
		physicsengine.h \
		ball.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o physicsengine.o physicsengine.cpp

ball.o: ball.cpp ../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QtGui \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessible.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessiblebridge.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbitmap.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qicon.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengine.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengineplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimageiohandler.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagewriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpicture.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpictureformatplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmapcache.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcursor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdrag.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericpluginfactory.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qinputmethod.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qkeysequence.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qoffscreensurface.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglcontext.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpalette.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qscreen.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsessionmanager.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstylehints.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurface.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurfaceformat.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtouchdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindow.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindowdefs.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericmatrix.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qquaternion.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengl.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglbuffer.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglframebufferobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglfunctions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpixeltransferoptions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglshaderprogram.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltexture.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltimerquery.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglversionfunctions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbackingstore.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbrush.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagedpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagelayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagesize.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintengine.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainterpath.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpdfwriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpen.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpolygon.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qregion.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrgb.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtransform.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qabstracttextdocumentlayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontdatabase.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontinfo.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qglyphrun.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrawfont.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstatictext.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextcursor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocument.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentfragment.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentwriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextformat.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlist.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextoption.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtexttable.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdesktopservices.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvalidator.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtguiversion.h \
		ball.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ball.o ball.cpp

vector.o: vector.cpp vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vector.o vector.cpp

car.o: car.cpp car.h \
		physicsengine.h \
		ball.h \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/QTimer \
		../../Qt/5.3/clang_64/lib/QtCore.framework/Versions/5/Headers/qtimer.h \
		vector.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/QtGui \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessible.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessiblebridge.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qaccessibleplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbitmap.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qicon.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengine.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qiconengineplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimage.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimageiohandler.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagereader.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qimagewriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmovie.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpicture.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpictureformatplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmap.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpixmapcache.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstandarditemmodel.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qclipboard.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcursor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdrag.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qevent.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericplugin.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericpluginfactory.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qguiapplication.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qinputmethod.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qkeysequence.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qoffscreensurface.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglcontext.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpalette.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qscreen.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsessionmanager.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstylehints.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurface.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsurfaceformat.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtouchdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindow.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qwindowdefs.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qgenericmatrix.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix4x4.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qquaternion.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector2d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector3d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvector4d.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengl.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglbuffer.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengldebug.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglframebufferobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglfunctions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglpixeltransferoptions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglshaderprogram.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltexture.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopengltimerquery.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglversionfunctions.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qopenglvertexarrayobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbackingstore.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qbrush.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qcolor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qmatrix.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagedpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagelayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpagesize.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintdevice.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpaintengine.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpainterpath.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpdfwriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpen.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qpolygon.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qregion.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrgb.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtransform.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qabstracttextdocumentlayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfont.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontdatabase.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontinfo.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qfontmetrics.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qglyphrun.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qrawfont.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qstatictext.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qsyntaxhighlighter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextcursor.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocument.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentfragment.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextdocumentwriter.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextformat.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlayout.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextlist.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextobject.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtextoption.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtexttable.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qdesktopservices.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qvalidator.h \
		../../Qt/5.3/clang_64/lib/QtGui.framework/Versions/5/Headers/qtguiversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o car.o car.cpp

moc_main.o: moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main.o moc_main.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/car || mkdir -p $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/car
	$(DEL_FILE) -r "$(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/car/car.app"
	
	-$(INSTALL_DIR) "car.app" "$(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/car/car.app"

uninstall_target: FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/car/car.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/car/ 


install_sources: first FORCE
	@test -d $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/. || mkdir -p $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/.
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/main.cpp $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/physicsengine.cpp $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/ball.cpp $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/vector.cpp $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/car.cpp $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/main.h $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/ball.h $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/car.h $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/vector.h $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./
	-$(INSTALL_FILE) /Users/Jc_tecklenburg/Git/genetic_cars/physicsengine.h $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./

uninstall_sources: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./physicsengine.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./vector.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./car.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./ball.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./main.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./car.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./vector.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./ball.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./physicsengine.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./main.cpp
	-$(DEL_DIR) $(INSTALL_ROOT)/Users/Jc_tecklenburg/Git/genetic_cars/./ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

